version: "3"

services:
  app:
    build:
      context: .
    container_name: app
    ports:
      - "8000:8001"
    volumes:
      - ./:/app
    env_file:
      - .env
    command: >
      sh -c "python3 manage.py wait_for_db &&
             python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8001
             celery -A book_library beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    depends_on:
      - db
      - redis

  celery:
    build: .
    command:
      celery -A book_library worker -l INFO &&
    volumes:
      - ./:/app
    depends_on:
      - app
      - redis
    env_file:
      - .env

  db:
    image: postgres:14-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"

  redis:
    image: "redis:alpine"
