# Generated by Django 4.2 on 2024-04-10 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0002_remove_borrowing_unique_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("PEN", "Pending"), ("PAID", "Paid")], max_length=4
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("PAY", "Payment"), ("FINE", "Fine")], max_length=4
                    ),
                ),
                ("session_url", models.URLField(max_length=300)),
                ("session_id", models.CharField(max_length=55)),
                ("money_to_pay", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "borrowing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="borrowings.borrowing",
                    ),
                ),
            ],
        ),
    ]
